export const LOGIN_USER = "LOGIN_USER"
export const CATCH_ERROR = "CATCH_ERROR"
export const USER_INFO = "USER_INFO"
export const DASH_INFO = "DASH_INFO"
export const START_TIMER = "START_TIMER"
export const CLEAR_HOUSE = "CLEAR_HOUSE"
